FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

USER 1001
EXPOSE 8080

COPY --chown=1001:root target/*-runner /work/application

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]